package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Affectation generated by hbm2java
 */
@Entity
@Table(name = "AFFECTATION", catalog = "ralidb")
public class Affectation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer affectationId ;
	private Date datedebutaffect;
	private Date datefinaffect;
	private Ressource ressource;
	private Phaseplanification phaseplanification;

	public Affectation() {
	}

	public Affectation(Integer affectationId) {
		this.affectationId = affectationId;
	}

	public Affectation(Integer affectationId, Date datedebutaffect,
			Date datefinaffect, Ressource ressource,
			Phaseplanification phaseplanification) {
		super();
		this.affectationId = affectationId;
		this.datedebutaffect = datedebutaffect;
		this.datefinaffect = datefinaffect;
		this.ressource = ressource;
		this.phaseplanification = phaseplanification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AFFECTATIONID", unique = true, nullable = false)
	public Integer getAffectationId() {
		return this.affectationId;
	}

	public void setAffectationId(Integer affectationId) {
		this.affectationId = affectationId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBUTAFFECT", length = 10)
	public Date getDatedebutaffect() {
		return this.datedebutaffect;
	}

	public void setDatedebutaffect(Date datedebutaffect) {
		this.datedebutaffect = datedebutaffect;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINAFFECT", length = 10)
	public Date getDatefinaffect() {
		return this.datefinaffect;
	}

	public void setDatefinaffect(Date datefinaffect) {
		this.datefinaffect = datefinaffect;
	}

	@ManyToOne
	@JoinColumn(name="IDRESS", referencedColumnName="IDRESS")
	public Ressource getRessource() {
		return ressource;
	}

	public void setRessource(Ressource ressource) {
		this.ressource = ressource;
	}
	
	@ManyToOne
	@JoinColumn(name="IDPHASE_P", referencedColumnName="IDPHASE_P")
	public Phaseplanification getPhaseplanification() {
		return phaseplanification;
	}

	public void setPhaseplanification(Phaseplanification phaseplanification) {
		this.phaseplanification = phaseplanification;
	}

}
