package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Amortissment generated by hbm2java
 */
@Entity
@Table(name = "AMORTISSMENT", catalog = "ralidb")
public class Amortissment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idamort;
//	private Integer idresshum;
//	private Integer idressamort;
	private String anneeamort;
	private Long valeuramort;
	private Ressamort ressamort;
	private Resshum resshum;	

	public Amortissment() {
	}

	public Amortissment(Integer idamort, String anneeamort, Long valeuramort,
			Ressamort ressamort, Resshum resshum) {
		super();
		this.idamort = idamort;
		this.anneeamort = anneeamort;
		this.valeuramort = valeuramort;
		this.ressamort = ressamort;
		this.resshum = resshum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDAMORT", unique = true, nullable = false)
	public Integer getIdamort() {
		return this.idamort;
	}

	public void setIdamort(Integer idamort) {
		this.idamort = idamort;
	}

//	@Column(name = "IDRESSHUM")
//	public Integer getIdresshum() {
//		return this.idresshum;
//	}
//
//	public void setIdresshum(Integer idresshum) {
//		this.idresshum = idresshum;
//	}
//
//	@Column(name = "IDRESSAMORT")
//	public Integer getIdressamort() {
//		return this.idressamort;
//	}
//
//	public void setIdressamort(Integer idressamort) {
//		this.idressamort = idressamort;
//	}

	@Column(name = "ANNEEAMORT", length = 65535)
	@Length(max = 65535)
	public String getAnneeamort() {
		return this.anneeamort;
	}

	public void setAnneeamort(String anneeamort) {
		this.anneeamort = anneeamort;
	}

	@Column(name = "VALEURAMORT", precision = 10, scale = 0)
	public Long getValeuramort() {
		return this.valeuramort;
	}

	public void setValeuramort(Long valeuramort) {
		this.valeuramort = valeuramort;
	}

	@ManyToOne
	@JoinColumn(name="IDRESSAMORT", referencedColumnName="IDRESS")
	public Ressamort getRessamort() {
		return ressamort;
	}

	public void setRessamort(Ressamort ressamort) {
		this.ressamort = ressamort;
	}

	@ManyToOne
	@JoinColumn(name="IDRESSHUM", referencedColumnName="IDRESS")
	public Resshum getResshum() {
		return resshum;
	}

	public void setResshum(Resshum resshum) {
		this.resshum = resshum;
	}
}
