package com.glaizer.RaliProject.model;


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Avoirdiplome generated by hbm2java
 */
@Entity
@Table(name = "AVOIRDIPLOME", catalog = "ralidb")
public class Avoirdiplome implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer avoirdiplomeId;
	private Date dateobtention;
	private Diplome diplome;
	private Resshum resshum;

	public Avoirdiplome() {
	}

	public Avoirdiplome(Integer avoirdiplomeId) {
		this.avoirdiplomeId = avoirdiplomeId;
	}
	
	public Avoirdiplome(Integer avoirdiplomeId, Date dateobtention, Diplome diplome,
			Resshum resshum) {
		super();
		this.avoirdiplomeId = avoirdiplomeId;
		this.dateobtention = dateobtention;
		this.diplome = diplome;
		this.resshum = resshum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AVOIRDIPLOMEID", unique = true, nullable = false)
	public Integer getId() {
		return this.avoirdiplomeId;
	}

	public void setId(Integer avoirdiplomeId) {
		this.avoirdiplomeId = avoirdiplomeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEOBTENTION", length = 10)
	public Date getDateobtention() {
		return this.dateobtention;
	}

	public void setDateobtention(Date dateobtention) {
		this.dateobtention = dateobtention;
	}
	
	@ManyToOne
	@JoinColumn(name="IDDIPLOME", referencedColumnName="IDDIPLOME")
	public Diplome getDiplome() {
		return diplome;
	}

	public void setDiplome(Diplome diplome) {
		this.diplome = diplome;
	}
	
	@ManyToOne
	@JoinColumn(name="IDRESS", referencedColumnName="IDRESS")
	public Resshum getResshum() {
		return resshum;
	}

	public void setResshum(Resshum resshum) {
		this.resshum = resshum;
	}
	
}
