package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Contenuoptimise generated by hbm2java
 */
@Entity
@Table(name = "CONTENUOPTIMISE", catalog = "ralidb")
public class Contenuoptimise implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer contenuoptimiseId ;
	private Long nbrheuresopt;
	private String commentaireopt;
	private Long tauxeligibilite;
	private Phaseretroplanification phaseretroplanification;
	private Jourssemaine jourssemaine;
	private Rapportactivites rapportactivites;
	private Tache tache;

	public Contenuoptimise() {
	}

	public Contenuoptimise(Integer contenuoptimiseId) {
		this.contenuoptimiseId =  contenuoptimiseId;
	}
	

	public Contenuoptimise(Integer contenuoptimiseId , Long nbrheuresopt,
			String commentaireopt, Long tauxeligibilite,
			Phaseretroplanification phaseretroplanification,
			Jourssemaine jourssemaine, Rapportactivites rapportactivites, Tache tache) {
		super();
		this.contenuoptimiseId = contenuoptimiseId;
		this.nbrheuresopt = nbrheuresopt;
		this.commentaireopt = commentaireopt;
		this.tauxeligibilite = tauxeligibilite;
		this.phaseretroplanification = phaseretroplanification;
		this.jourssemaine = jourssemaine;
		this.rapportactivites = rapportactivites;
		this.tache  = tache;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CONTENUOPTIMISEID", unique = true, nullable = false)
	public Integer getContenuoptimiseId() {
		return this.contenuoptimiseId;
	}

	public void setContenuoptimiseId(Integer contenuoptimiseId ) {
		this.contenuoptimiseId = contenuoptimiseId;
	}

	@Column(name = "NBRHEURESOPT", precision = 10, scale = 0)
	public Long getNbrheuresopt() {
		return this.nbrheuresopt;
	}

	public void setNbrheuresopt(Long nbrheuresopt) {
		this.nbrheuresopt = nbrheuresopt;
	}

	@Column(name = "COMMENTAIREOPT", length = 65535)
	@Length(max = 65535)
	public String getCommentaireopt() {
		return this.commentaireopt;
	}

	public void setCommentaireopt(String commentaireopt) {
		this.commentaireopt = commentaireopt;
	}

	@Column(name = "TAUXELIGIBILITE", precision = 10, scale = 0)
	public Long getTauxeligibilite() {
		return this.tauxeligibilite;
	}

	public void setTauxeligibilite(Long tauxeligibilite) {
		this.tauxeligibilite = tauxeligibilite;
	}

	@ManyToOne
	@JoinColumn(name="IDPHASE_RP", referencedColumnName="IDPHASE_RP")
	public Phaseretroplanification getPhaseretroplanification() {
		return phaseretroplanification;
	}

	public void setPhaseretroplanification(
			Phaseretroplanification phaseretroplanification) {
		this.phaseretroplanification = phaseretroplanification;
	}
	
	@ManyToOne
	@JoinColumn(name="IDJOUR", referencedColumnName="IDJOUR")
	public Jourssemaine getJourssemaine() {
		return jourssemaine;
	}

	public void setJourssemaine(Jourssemaine jourssemaine) {
		this.jourssemaine = jourssemaine;
	}

	@ManyToOne
	@JoinColumn(name="IDRAPACTV", referencedColumnName="IDRAPACTV")
	public Rapportactivites getRapportactivites() {
		return rapportactivites;
	}

	public void setRapportactivites(Rapportactivites rapportactivites) {
		this.rapportactivites = rapportactivites;
	}
	
	@ManyToOne
	@JoinColumn(name="IDTACHE", referencedColumnName="IDTACHE")
	public Tache getTache() {
		return tache;
	}

	public void setTache(Tache tache) {
		this.tache = tache;
	}
	
	
}
