package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Contenu generated by hbm2java
 */
@Entity
@Table(name = "CONTENU", catalog = "ralidb")
public class Contenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer contenuId ;
	private Double nbrheure;
	private String commentaire;
	private Jourssemaine jourssemaine;
	private Rapportactivites rapportactivites;
	private Phaseplanification phaseplanification;
	private Tache tache; 

	public Contenu() {
	}

	public Contenu(Integer contenuId) {
		this.contenuId = contenuId;
	}	

	public Contenu(Integer contenuId, Double nbrheure, String commentaire,
			Jourssemaine jourssemaine, Rapportactivites rapportactivites,
			Phaseplanification phaseplanification, Tache tache) {
		super();
		this.contenuId = contenuId;
		this.nbrheure = nbrheure;
		this.commentaire = commentaire;
		this.jourssemaine = jourssemaine;
		this.rapportactivites = rapportactivites;
		this.phaseplanification = phaseplanification;
		this.tache  = tache;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CONTENUID", unique = true, nullable = false)
	public Integer getContenuId() {
		return this.contenuId;
	}

	public void setContenuId(Integer contenuId ) {
		this.contenuId = contenuId;
	}

	@Column(name = "NBRHEURE", precision = 10, scale = 0)
	public Double getNbrheure() {
		return this.nbrheure;
	}

	public void setNbrheure(Double nbrheure) {
		this.nbrheure = nbrheure;
	}

	@Column(name = "COMMENTAIRE", length = 65535)
	@Length(max = 65535)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@ManyToOne
	@JoinColumn(name="IDJOUR", referencedColumnName="IDJOUR")	
	public Jourssemaine getJourssemaine() {
		return jourssemaine;
	}

	public void setJourssemaine(Jourssemaine jourssemaine) {
		this.jourssemaine = jourssemaine;
	}

	@ManyToOne
	@JoinColumn(name="IDRAPACTV", referencedColumnName="IDRAPACTV")	
	public Rapportactivites getRapportactivites() {
		return rapportactivites;
	}

	public void setRapportactivites(Rapportactivites rapportactivites) {
		this.rapportactivites = rapportactivites;
	}

	@ManyToOne
	@JoinColumn(name="IDPHASE_P", referencedColumnName="IDPHASE_P")
	public Phaseplanification getPhaseplanification() {
		return phaseplanification;
	}

	public void setPhaseplanification(Phaseplanification phaseplanification) {
		this.phaseplanification = phaseplanification;
	}

	@ManyToOne
	@JoinColumn(name="IDTACHE", referencedColumnName="IDTACHE")
	public Tache getTache() {
		return tache;
	}

	public void setTache(Tache tache) {
		this.tache = tache;
	}

	@Override
	public String toString() {
		return "Contenu [ContenuId=" + contenuId + ", commentaire="
				+ commentaire + ", jourssemaine=" + jourssemaine
				+ ", nbrheure=" + nbrheure + ", phaseplanification="
				+ phaseplanification + ", rapportactivites=" + rapportactivites + ", tache=" + tache
				+ "]";
	}

	
	
}
