package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Coordonnees generated by hbm2java
 */
@Entity
@Table(name = "COORDONNEES", catalog = "ralidb")
public class Coordonnees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idcoord;
//	private int idtypecoord;
//	private int idress;
	private String valcoord;
	private Typecoordonnees typecoordonnee;
	private Resshum resshum;

	public Coordonnees() {
	}
	
	public Coordonnees(Integer idcoord, String valcoord,
			Typecoordonnees typecoordonnee, Resshum resshum) {
		super();
		this.idcoord = idcoord;
		this.valcoord = valcoord;
		this.typecoordonnee = typecoordonnee;
		this.resshum = resshum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDCOORD", unique = true, nullable = false)
	public Integer getIdcoord() {
		return this.idcoord;
	}

	public void setIdcoord(Integer idcoord) {
		this.idcoord = idcoord;
	}

//	@Column(name = "IDTYPECOORD", nullable = false)
//	public int getIdtypecoord() {
//		return this.idtypecoord;
//	}
//
//	public void setIdtypecoord(int idtypecoord) {
//		this.idtypecoord = idtypecoord;
//	}
//
//	@Column(name = "IDRESS", nullable = false)
//	public int getIdress() {
//		return this.idress;
//	}
//
//	public void setIdress(int idress) {
//		this.idress = idress;
//	}

	@Column(name = "VALCOORD", length = 65535)
	@Length(max = 65535)
	public String getValcoord() {
		return this.valcoord;
	}

	public void setValcoord(String valcoord) {
		this.valcoord = valcoord;
	}

	@ManyToOne
	@JoinColumn(name="IDTYPECOORD", referencedColumnName="IDTYPECOORD")
	public Typecoordonnees getTypecoordonnee() {
		return typecoordonnee;
	}

	public void setTypecoordonnee(Typecoordonnees typecoordonnee) {
		this.typecoordonnee = typecoordonnee;
	}

	@ManyToOne
	@JoinColumn(name="IDRESS", referencedColumnName="IDRESS")
	public Resshum getResshum() {
		return resshum;
	}

	public void setResshum(Resshum resshum) {
		this.resshum = resshum;
	}
	
}
