package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Cv generated by hbm2java
 */
@Entity
@Table(name = "CV", catalog = "ralidb")
public class Cv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idcv;
//	private int idress;
	private Date datemiseenligne;
	private String lienverssfCv;
	private Resshum resshum;

	public Cv() {
	}

	public Cv(int idcv) {
		this.idcv = idcv;
	}

	public Cv(Integer idcv, Date datemiseenligne,
			String lienverssfCv, Resshum resshum) {
		super();
		this.idcv = idcv;
		this.datemiseenligne = datemiseenligne;
		this.lienverssfCv = lienverssfCv;
		this.resshum = resshum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDCV", unique = true, nullable = false)
	public Integer getIdcv() {
		return this.idcv;
	}

	public void setIdcv(Integer idcv) {
		this.idcv = idcv;
	}

//	@Column(name = "IDRESS", nullable = false)
//	public int getIdress() {
//		return this.idress;
//	}
//
//	public void setIdress(int idress) {
//		this.idress = idress;
//	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEMISEENLIGNE", length = 10)
	public Date getDatemiseenligne() {
		return this.datemiseenligne;
	}

	public void setDatemiseenligne(Date datemiseenligne) {
		this.datemiseenligne = datemiseenligne;
	}

	@Column(name = "LIENVERSSF_CV", length = 65535)
	@Length(max = 65535)
	public String getLienverssfCv() {
		return this.lienverssfCv;
	}

	public void setLienverssfCv(String lienverssfCv) {
		this.lienverssfCv = lienverssfCv;
	}

	@OneToOne
	@JoinColumn(name="IDRESS", referencedColumnName="IDRESS")
	public Resshum getResshum() {
		return resshum;
	}

	public void setResshum(Resshum resshum) {
		this.resshum = resshum;
	}
}
