package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.jboss.seam.annotations.Name;

/**
 * Diplome generated by hbm2java
 */
@Entity
@Table(name = "DIPLOME", catalog = "ralidb")
@Name("Diplome")
public class Diplome implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer iddiplome;
	private String lbldiplome;
	private List<Avoirdiplome> resshums;

	public Diplome() {
	}
	
	public Diplome(Integer iddiplome, String lbldiplome,
			List<Avoirdiplome> resshums) {
		super();
		this.iddiplome = iddiplome;
		this.lbldiplome = lbldiplome;
		this.resshums = resshums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDDIPLOME", unique = true, nullable = false)
	public Integer getIddiplome() {
		return this.iddiplome;
	}

	public void setIddiplome(Integer iddiplome) {
		this.iddiplome = iddiplome;
	}

	@Column(name = "LBLDIPLOME", length = 65535)
	@Length(max = 65535)
	public String getLbldiplome() {
		return this.lbldiplome;
	}

	public void setLbldiplome(String lbldiplome) {
		this.lbldiplome = lbldiplome;
	}
	
	@OneToMany(mappedBy="diplome")
	public List<Avoirdiplome> getResshums() {
		return resshums;
	}

	public void setResshums(List<Avoirdiplome> resshums) {
		this.resshums = resshums;
	}
}
