package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Documentationphase generated by hbm2java
 */
@Entity
@Table(name = "DOCUMENTATIONPHASE", catalog = "ralidb")
public class Documentationphase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer iddoc;
//	private Integer idphaseRp;
//	private Integer idphaseP;
	private String lbldoc;
	private String descdoc;
	private Date datemiseenlignedoc;
	private String lienversSfDoc;
	private Phaseplanification phaseplanification;
	private Phaseretroplanification phaseretroplanification;

	public Documentationphase() {
	}

	public Documentationphase(Integer iddoc, String lbldoc, String descdoc,
			Date datemiseenlignedoc, String lienversSfDoc,
			Phaseplanification phaseplanification,
			Phaseretroplanification phaseretroplanification) {
		super();
		this.iddoc = iddoc;
		this.lbldoc = lbldoc;
		this.descdoc = descdoc;
		this.datemiseenlignedoc = datemiseenlignedoc;
		this.lienversSfDoc = lienversSfDoc;
		this.phaseplanification = phaseplanification;
		this.phaseretroplanification = phaseretroplanification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDDOC", unique = true, nullable = false)
	public Integer getIddoc() {
		return this.iddoc;
	}

	public void setIddoc(Integer iddoc) {
		this.iddoc = iddoc;
	}

//	@Column(name = "IDPHASE_RP")
//	public Integer getIdphaseRp() {
//		return this.idphaseRp;
//	}
//	
//	public void setIdphaseRp(Integer idphaseRp) {
//		this.idphaseRp = idphaseRp;
//	}
//
//	@Column(name = "IDPHASE_P")
//	public Integer getIdphaseP() {
//		return this.idphaseP;
//	}
//
//	public void setIdphaseP(Integer idphaseP) {
//		this.idphaseP = idphaseP;
//	}

	@Column(name = "LBLDOC", length = 65535)
	@Length(max = 65535)
	public String getLbldoc() {
		return this.lbldoc;
	}

	public void setLbldoc(String lbldoc) {
		this.lbldoc = lbldoc;
	}

	@Column(name = "DESCDOC", length = 65535)
	@Length(max = 65535)
	public String getDescdoc() {
		return this.descdoc;
	}

	public void setDescdoc(String descdoc) {
		this.descdoc = descdoc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEMISEENLIGNEDOC", length = 10)
	public Date getDatemiseenlignedoc() {
		return this.datemiseenlignedoc;
	}

	public void setDatemiseenlignedoc(Date datemiseenlignedoc) {
		this.datemiseenlignedoc = datemiseenlignedoc;
	}

	@Column(name = "LIENVERS_SF_DOC", length = 65535)
	@Length(max = 65535)
	public String getLienversSfDoc() {
		return this.lienversSfDoc;
	}

	public void setLienversSfDoc(String lienversSfDoc) {
		this.lienversSfDoc = lienversSfDoc;
	}

	@ManyToOne
	@JoinColumn(name="IDPHASE_P", referencedColumnName="IDPHASE_P")
	public Phaseplanification getPhaseplanification() {
		return phaseplanification;
	}

	public void setPhaseplanification(Phaseplanification phaseplanification) {
		this.phaseplanification = phaseplanification;
	}

	@ManyToOne
	@JoinColumn(name="IDPHASE_RP", referencedColumnName="IDPHASE_RP")
	public Phaseretroplanification getPhaseretroplanification() {
		return phaseretroplanification;
	}

	public void setPhaseretroplanification(Phaseretroplanification phaseretroplanification) {
		this.phaseretroplanification = phaseretroplanification;
	}
}
