package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;


/**
 * Dossiercac generated by hbm2java
 */
@Entity
@Table(name = "DOSSIERCAC", catalog = "ralidb")
public class Dossiercac implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer dossierCacId;
	private String anneedosscac;
	private Entreprise entreprise;
	private Ggpsysteme ggpsysteme;
	private Icac icac;
	

	public Dossiercac() {
	}

	public Dossiercac(Integer dossierCacId) {
		this.dossierCacId = dossierCacId;
	}

	public Dossiercac(Integer dossierCacId , String anneedosscac,
			Entreprise entreprise, Ggpsysteme ggpsysteme, Icac icac) {
		super();
		this.dossierCacId = dossierCacId;
		this.anneedosscac = anneedosscac;
		this.entreprise = entreprise;
		this.ggpsysteme = ggpsysteme;
		this.icac = icac;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DOSSIERCACID", unique = true, nullable = false)
	public Integer getDossierCacId() {
		return this.dossierCacId;
	}

	public void setDossierCacId(Integer dossierCacId) {
		this.dossierCacId = dossierCacId;
	}

	@Column(name = "ANNEEDOSSCAC", length = 65535)
	@Length(max = 65535)
	public String getAnneedosscac() {
		return this.anneedosscac;
	}

	public void setAnneedosscac(String anneedosscac) {
		this.anneedosscac = anneedosscac;
	}
	
	@ManyToOne
	@JoinColumn(name="IDENTREPRISE", referencedColumnName="IDENTREPRISE")
	public Entreprise getEntreprise() {
		return entreprise;
	}

	public void setEntreprise(Entreprise entreprise) {
		this.entreprise = entreprise;
	}

	@ManyToOne
	@JoinColumn(name="IDGGPS", referencedColumnName="IDGGPS")	
	public Ggpsysteme getGgpsysteme() {
		return ggpsysteme;
	}

	public void setGgpsysteme(Ggpsysteme ggpsysteme) {
		this.ggpsysteme = ggpsysteme;
	}

	@ManyToOne
	@JoinColumn(name="IDICAC", referencedColumnName="IDICAC")	
	public Icac getIcac() {
		return icac;
	}

	public void setIcac(Icac icac) {
		this.icac = icac;
	}	
	
}
