package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Entreprise generated by hbm2java
 */
@Entity
@Table(name = "ENTREPRISE", catalog = "ralidb")
public class Entreprise implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int identreprise;
	private String nomentreprise;
	private String logingentreprise;
	private Boolean isjei;
	private Integer nbrjourstrav;
	private String premierannecir;
	private Boolean hasaccesstoicac;
	private Boolean hasacesstoraoptim;
	private Boolean hasacesstoretroplanif;
	private List<Dossiercac> icacs;
	private List<Dossiercac> ggpsystemesCac;
	private List<Organisation> organisations;
	private List<Dossiercir> simulationscirScirs;
	private List<Dossiercir> ggpsystemesCir;

	public Entreprise() {
	}

	public Entreprise(int identreprise) {
		this.identreprise = identreprise;
	}

	public Entreprise(int identreprise,String nomentreprise, String logingentreprise, Boolean isjei,
			Integer nbrjourstrav, String premierannecir,
			Boolean hasaccesstoicac, Boolean hasacesstoraoptim,
			Boolean hasacesstoretroplanif, List<Dossiercac> icacs,
			List<Dossiercac> ggpsystemesCac, List<Organisation> organisations,
			List<Dossiercir> simulationscirScirs,
			List<Dossiercir> ggpsystemesCir) {
		super();
		this.identreprise = identreprise;
		this.nomentreprise= nomentreprise;
		this.logingentreprise = logingentreprise;
		this.isjei = isjei;
		this.nbrjourstrav = nbrjourstrav;
		this.premierannecir = premierannecir;
		this.hasaccesstoicac = hasaccesstoicac;
		this.hasacesstoraoptim = hasacesstoraoptim;
		this.hasacesstoretroplanif = hasacesstoretroplanif;
		this.icacs = icacs;
		this.ggpsystemesCac = ggpsystemesCac;
		this.organisations = organisations;
		this.simulationscirScirs = simulationscirScirs;
		this.ggpsystemesCir = ggpsystemesCir;
	}

	@Id
	@Column(name = "IDENTREPRISE", unique = true, nullable = false)
	public int getIdentreprise() {
		return this.identreprise;
	}

	public void setIdentreprise(int identreprise) {
		this.identreprise = identreprise;
	}
	@Column(name = "NOMENTREPRISE", length = 65535)
	@Length(max = 65535)
	public String getNomentreprise() {
		return this.nomentreprise;
	}

	public void setNomentreprise(String nomentreprise) {
		this.nomentreprise = nomentreprise;
	}

	@Column(name = "LOGINGENTREPRISE", length = 65535)
	@Length(max = 65535)
	public String getLogingentreprise() {
		return this.logingentreprise;
	}

	public void setLogingentreprise(String logingentreprise) {
		this.logingentreprise = logingentreprise;
	}

	@Column(name = "ISJEI")
	public Boolean getIsjei() {
		return this.isjei;
	}

	public void setIsjei(Boolean isjei) {
		this.isjei = isjei;
	}

	@Column(name = "NBRJOURSTRAV")
	public Integer getNbrjourstrav() {
		return this.nbrjourstrav;
	}

	public void setNbrjourstrav(Integer nbrjourstrav) {
		this.nbrjourstrav = nbrjourstrav;
	}

	@Column(name = "PREMIERANNECIR", length = 65535)
	@Length(max = 65535)
	public String getPremierannecir() {
		return this.premierannecir;
	}

	public void setPremierannecir(String premierannecir) {
		this.premierannecir = premierannecir;
	}

	@Column(name = "HASACCESSTOICAC")
	public Boolean getHasaccesstoicac() {
		return this.hasaccesstoicac;
	}

	public void setHasaccesstoicac(Boolean hasaccesstoicac) {
		this.hasaccesstoicac = hasaccesstoicac;
	}

	@Column(name = "HASACESSTORAOPTIM")
	public Boolean getHasacesstoraoptim() {
		return this.hasacesstoraoptim;
	}

	public void setHasacesstoraoptim(Boolean hasacesstoraoptim) {
		this.hasacesstoraoptim = hasacesstoraoptim;
	}

	@Column(name = "HASACESSTORETROPLANIF")
	public Boolean getHasacesstoretroplanif() {
		return this.hasacesstoretroplanif;
	}

	public void setHasacesstoretroplanif(Boolean hasacesstoretroplanif) {
		this.hasacesstoretroplanif = hasacesstoretroplanif;
	}
	
	@OneToMany(mappedBy="entreprise")
	public List<Dossiercac> getIcacs() {
		return icacs;
	}

	public void setIcacs(List<Dossiercac> icacs) {
		this.icacs = icacs;
	}

	@OneToMany(mappedBy="entreprise")
	public List<Dossiercac> getGgpsystemesCac() {
		return ggpsystemesCac;
	}

	public void setGgpsystemesCac(List<Dossiercac> ggpsystemesCac) {
		this.ggpsystemesCac = ggpsystemesCac;
	}

	@OneToMany(mappedBy="entreprise")
	public List<Organisation> getOrganisations() {
		return organisations;
	}

	public void setOrganisations(List<Organisation> organisations) {
		this.organisations = organisations;
	}
	
	@OneToMany(mappedBy="entreprise")
	public List<Dossiercir> getSimulationscirScirs() {
		return simulationscirScirs;
	}

	public void setSimulationscirScirs(List<Dossiercir> simulationscirScirs) {
		this.simulationscirScirs = simulationscirScirs;
	}
	
	@OneToMany(mappedBy="entreprise")
	public List<Dossiercir> getGgpsystemesCir() {
		return ggpsystemesCir;
	}

	public void setGgpsystemesCir(List<Dossiercir> ggpsystemesCir) {
		this.ggpsystemesCir = ggpsystemesCir;
	}

	@Override
	public String toString() {
		return "Entreprise [ggpsystemesCac=" + ggpsystemesCac
				+ ", ggpsystemesCir=" + ggpsystemesCir + ", hasaccesstoicac="
				+ hasaccesstoicac + ", hasacesstoraoptim=" + hasacesstoraoptim
				+ ", hasacesstoretroplanif=" + hasacesstoretroplanif
				+ ", icacs=" + icacs + ", identreprise=" + identreprise
				+ ", isjei=" + isjei + ", logingentreprise=" + logingentreprise
				+ ", nbrjourstrav=" + nbrjourstrav + ", nomentreprise="
				+ nomentreprise + ", organisations=" + organisations
				+ ", premierannecir=" + premierannecir
				+ ", simulationscirScirs=" + simulationscirScirs + "]";
	}

		
	
}
