package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Etatphase generated by hbm2java
 */
@Entity
@Table(name = "ETATPHASE", catalog = "ralidb")
public class Etatphase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idetatphase;
	private String lbletatphase;
	private List<PhaseRpAvoirEtat> Phasesretroplanifications;	
	private List<PhasePAvoirEtat> phasesplanifications;

	public Etatphase() {
	}

	public Etatphase(Integer idetatphase, String lbletatphase,
			List<PhaseRpAvoirEtat> phasesretroplanifications,
			List<PhasePAvoirEtat> phasesplanifications) {
		super();
		this.idetatphase = idetatphase;
		this.lbletatphase = lbletatphase;
		Phasesretroplanifications = phasesretroplanifications;
		this.phasesplanifications = phasesplanifications;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDETATPHASE", unique = true, nullable = false)
	public Integer getIdetatphase() {
		return this.idetatphase;
	}

	public void setIdetatphase(Integer idetatphase) {
		this.idetatphase = idetatphase;
	}

	@Column(name = "LBLETATPHASE", length = 65535)
	@Length(max = 65535)
	public String getLbletatphase() {
		return this.lbletatphase;
	}

	public void setLbletatphase(String lbletatphase) {
		this.lbletatphase = lbletatphase;
	}

	@OneToMany(mappedBy="etatphase")
	public List<PhaseRpAvoirEtat> getPhasesretroplanifications() {
		return Phasesretroplanifications;
	}

	public void setPhasesretroplanifications(
			List<PhaseRpAvoirEtat> phasesretroplanifications) {
		Phasesretroplanifications = phasesretroplanifications;
	}

	@OneToMany(mappedBy="etatphase")
	public List<PhasePAvoirEtat> getPhasesplanifications() {
		return phasesplanifications;
	}

	public void setPhasesplanifications(List<PhasePAvoirEtat> phasesplanifications) {
		this.phasesplanifications = phasesplanifications;
	}
}
