package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GgpsAvoirProfil generated by hbm2java
 */
@Entity
@Table(name = "GGPS_AVOIR_PROFIL", catalog = "ralidb")
public class GgpsAvoirProfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer ggpsAvoirProfilId;
	private int idggps;
	private int idprofil;

	public GgpsAvoirProfil() {
	}

	public GgpsAvoirProfil(Integer ggpsAvoirProfilId) {
		this.ggpsAvoirProfilId = ggpsAvoirProfilId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "GGPSAVOIRPROFILID", unique = true, nullable = false)
	public Integer getGgpsAvoirProfilId() {
		return this.ggpsAvoirProfilId;
	}

	public void setGgpsAvoirProfilId(Integer ggpsAvoirProfilId) {
		this.ggpsAvoirProfilId = ggpsAvoirProfilId;
	}

	public void setIdggps(int idggps) {
		this.idggps = idggps;
	}

	public int getIdggps() {
		return idggps;
	}

	public void setIdprofil(int idprofil) {
		this.idprofil = idprofil;
	}

	public int getIdprofil() {
		return idprofil;
	}
}
