package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Icac generated by hbm2java
 */
@Entity
@Table(name = "ICAC", catalog = "ralidb")
public class Icac implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idicac;
	private Date dateIcac;
	private String lienSfDeprd;
	private String lienSfDepri;
	private List<Dossiercac> ggpsystemes;	
	private List<Dossiercac> entreprises;

	public Icac() {
	}

	public Icac(Integer idicac, Date dateIcac, String lienSfDeprd,
			String lienSfDepri, List<Dossiercac> ggpsystemes,
			List<Dossiercac> entreprises) {
		super();
		this.idicac = idicac;
		this.dateIcac = dateIcac;
		this.lienSfDeprd = lienSfDeprd;
		this.lienSfDepri = lienSfDepri;
		this.ggpsystemes = ggpsystemes;
		this.entreprises = entreprises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDICAC", unique = true, nullable = false)
	public Integer getIdicac() {
		return this.idicac;
	}

	public void setIdicac(Integer idicac) {
		this.idicac = idicac;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ICAC", length = 10)
	public Date getDateIcac() {
		return this.dateIcac;
	}

	public void setDateIcac(Date dateIcac) {
		this.dateIcac = dateIcac;
	}

	@Column(name = "LIEN_SF_DEPRD", length = 65535)
	@Length(max = 65535)
	public String getLienSfDeprd() {
		return this.lienSfDeprd;
	}

	public void setLienSfDeprd(String lienSfDeprd) {
		this.lienSfDeprd = lienSfDeprd;
	}

	@Column(name = "LIEN_SF_DEPRI", length = 65535)
	@Length(max = 65535)
	public String getLienSfDepri() {
		return this.lienSfDepri;
	}

	public void setLienSfDepri(String lienSfDepri) {
		this.lienSfDepri = lienSfDepri;
	}

	@OneToMany(mappedBy="icac")
	public List<Dossiercac> getGgpsystemes() {
		return ggpsystemes;
	}

	public void setGgpsystemes(List<Dossiercac> ggpsystemes) {
		this.ggpsystemes = ggpsystemes;
	}
	
	@OneToMany(mappedBy="icac")
	public List<Dossiercac> getEntreprises() {
		return entreprises;
	}

	public void setEntreprises(List<Dossiercac> entreprises) {
		this.entreprises = entreprises;
	}	
}
