package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Jourssemaine generated by hbm2java
 */
@Entity
@Table(name = "JOURSSEMAINE", catalog = "ralidb")
public class Jourssemaine implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idjour;
	private String nomjour;
	private List<Contenuoptimise> rapportsactivitesOptm;
	private List<Contenuoptimise> phasesretroplanification;	
	private List<Joursouvresorg> organisations;
	private List<Contenu> rapportsactivites;
	private List<Contenu> phasesplanification;

	public Jourssemaine() {
	}

	public Jourssemaine(Integer idjour, String nomjour,
			List<Contenuoptimise> rapportsactivitesOptm,
			List<Contenuoptimise> phasesretroplanification,
			List<Joursouvresorg> organisations,
			List<Contenu> rapportsactivites, List<Contenu> phasesplanification) {
		super();
		this.idjour = idjour;
		this.nomjour = nomjour;
		this.rapportsactivitesOptm = rapportsactivitesOptm;
		this.phasesretroplanification = phasesretroplanification;
		this.organisations = organisations;
		this.rapportsactivites = rapportsactivites;
		this.phasesplanification = phasesplanification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDJOUR", unique = true, nullable = false)
	public Integer getIdjour() {
		return this.idjour;
	}

	public void setIdjour(Integer idjour) {
		this.idjour = idjour;
	}

	@Column(name = "NOMJOUR", length = 65535)
	@Length(max = 65535)
	public String getNomjour() {
		return this.nomjour;
	}

	public void setNomjour(String nomjour) {
		this.nomjour = nomjour;
	}

	@OneToMany(mappedBy="jourssemaine")
	public List<Contenuoptimise> getRapportsactivitesOptm() {
		return rapportsactivitesOptm;
	}

	public void setRapportsactivitesOptm(List<Contenuoptimise> rapportsactivitesOptm) {
		this.rapportsactivitesOptm = rapportsactivitesOptm;
	}

	@OneToMany(mappedBy="jourssemaine")
	public List<Contenuoptimise> getPhasesretroplanification() {
		return phasesretroplanification;
	}

	public void setPhasesretroplanification(
			List<Contenuoptimise> phasesretroplanification) {
		this.phasesretroplanification = phasesretroplanification;
	}
	
	@OneToMany(mappedBy="jourssemaine")
	public List<Joursouvresorg> getOrganisations() {
		return organisations;
	}

	public void setOrganisations(List<Joursouvresorg> organisations) {
		this.organisations = organisations;
	}
	
	@OneToMany(mappedBy="jourssemaine")
	public List<Contenu> getRapportsactivites() {
		return rapportsactivites;
	}

	public void setRapportsactivites(List<Contenu> rapportsactivites) {
		this.rapportsactivites = rapportsactivites;
	}
	
	@OneToMany(mappedBy="jourssemaine")
	public List<Contenu> getPhasesplanification() {
		return phasesplanification;
	}

	public void setPhasesplanification(List<Contenu> phasesplanification) {
		this.phasesplanification = phasesplanification;
	}
}
