package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Joursouvresorg generated by hbm2java
 */
@Entity
@Table(name = "JOURSOUVRESORG", catalog = "ralidb")
public class Joursouvresorg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer  joursouvresorgId ;
	private Boolean isworkingdayorg;
	private Organisation organisation;
	private Jourssemaine jourssemaine;

	public Joursouvresorg() {
	}

	public Joursouvresorg(Integer joursouvresorgId ) {
		this.joursouvresorgId = joursouvresorgId;
	}
	
	public Joursouvresorg(Integer  joursouvresorgId, Boolean isworkingdayorg,
			Organisation organisation, Jourssemaine jourssemaine) {
		super();
		this.joursouvresorgId = joursouvresorgId;
		this.isworkingdayorg = isworkingdayorg;
		this.organisation = organisation;
		this.jourssemaine = jourssemaine;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "JOURSOUVRESORGID", unique = true, nullable = false)
	public Integer getJoursouvresorgId() {
		return this.joursouvresorgId;
	}

	public void setJoursouvresorgId(Integer joursouvresorgId ) {
		this.joursouvresorgId = joursouvresorgId;
	}

	@Column(name = "ISWORKINGDAYORG")
	public Boolean getIsworkingdayorg() {
		return this.isworkingdayorg;
	}

	public void setIsworkingdayorg(Boolean isworkingdayorg) {
		this.isworkingdayorg = isworkingdayorg;
	}

	@ManyToOne
	@JoinColumn(name="IDORG", referencedColumnName="IDORG")
	public Organisation getOrganisation() {
		return organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}
	
	@ManyToOne
	@JoinColumn(name="IDJOUR", referencedColumnName="IDJOUR")
	public Jourssemaine getJourssemaine() {
		return jourssemaine;
	}

	public void setJourssemaine(Jourssemaine jourssemaine) {
		this.jourssemaine = jourssemaine;
	}
}
