package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Organisation generated by hbm2java
 */
@Entity
@Table(name = "ORGANISATION", catalog = "ralidb")
public class Organisation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idorg;
	private String lblorg;
	private Integer profondeurorg;
	private Boolean isentreprise;
	private Boolean isintegfiscal;
	private Organisation organisation;
	private List<Joursouvresorg> jourssemaine;
	private List<Ressource> ressources;
	private Entreprise entreprise;
	private List<Prestation> prestations;
	private List<Organisation> organisations;

	public Organisation() {
	}

	public Organisation(int idorg) {
		this.idorg = idorg;
	}

	public Organisation(int idorg, String lblorg, Integer profondeurorg,
			Boolean isentreprise, Boolean isintegfiscal,
			Organisation organisation, List<Joursouvresorg> jourssemaine,
			List<Ressource> ressources, Entreprise entreprise,
			List<Prestation> prestations, List<Organisation> organisations) {
		super();
		this.idorg = idorg;
		this.lblorg = lblorg;
		this.profondeurorg = profondeurorg;
		this.isentreprise = isentreprise;
		this.isintegfiscal = isintegfiscal;
		this.organisation = organisation;
		this.jourssemaine = jourssemaine;
		this.ressources = ressources;
		this.entreprise = entreprise;
		this.prestations = prestations;
		this.organisations = organisations;
	}

	@Id
	@Column(name = "IDORG", unique = true, nullable = false)
	public int getIdorg() {
		return this.idorg;
	}

	public void setIdorg(int idorg) {
		this.idorg = idorg;
	}

	@Column(name = "LBLORG", length = 65535)
	@Length(max = 65535)
	public String getLblorg() {
		return this.lblorg;
	}

	public void setLblorg(String lblorg) {
		this.lblorg = lblorg;
	}

	@Column(name = "PROFONDEURORG")
	public Integer getProfondeurorg() {
		return this.profondeurorg;
	}

	public void setProfondeurorg(Integer profondeurorg) {
		this.profondeurorg = profondeurorg;
	}

	@Column(name = "ISENTREPRISE")
	public Boolean getIsentreprise() {
		return this.isentreprise;
	}

	public void setIsentreprise(Boolean isentreprise) {
		this.isentreprise = isentreprise;
	}

	@Column(name = "ISINTEGFISCAL")
	public Boolean getIsintegfiscal() {
		return this.isintegfiscal;
	}

	public void setIsintegfiscal(Boolean isintegfiscal) {
		this.isintegfiscal = isintegfiscal;
	}
	
	@ManyToOne
	@JoinColumn(name="IDORG_PERE", referencedColumnName="IDORG")
	public Organisation getOrganisation() {
		return organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@OneToMany(mappedBy="organisation")
	public List<Joursouvresorg> getJourssemaine() {
		return jourssemaine;
	}

	public void setJourssemaine(List<Joursouvresorg> jourssemaine) {
		this.jourssemaine = jourssemaine;
	}

	@OneToMany(mappedBy="organisation")
	public List<Ressource> getRessources() {
		return ressources;
	}

	public void setRessources(List<Ressource> ressources) {
		this.ressources = ressources;
	}

	@ManyToOne
	@JoinColumn(name="IDENTREPRISE", referencedColumnName="IDENTREPRISE")
	public Entreprise getEntreprise() {
		return entreprise;
	}

	public void setEntreprise(Entreprise entreprise) {
		this.entreprise = entreprise;
	}

	@OneToMany(mappedBy="organisation")
	public List<Prestation> getPrestations() {
		return prestations;
	}

	public void setPrestations(List<Prestation> prestations) {
		this.prestations = prestations;
	}

	@OneToMany(mappedBy="organisation")
	public List<Organisation> getOrganisations() {
		return organisations;
	}

	public void setOrganisations(List<Organisation> organisations) {
		this.organisations = organisations;
	}
}
