package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhasePAvoirEtat generated by hbm2java
 */
@Entity
@Table(name = "PHASE_P_AVOIR_ETAT", catalog = "ralidb")
public class PhasePAvoirEtat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer phasePAvoirEtatId ;
	private Date PAvoirEtatFrom;
	private Date PAvoirEtatTo;
	private Phaseplanification phaseplanification;
	private Etatphase etatphase;

	public PhasePAvoirEtat() {
	}

	public PhasePAvoirEtat(Integer phasePAvoirEtatId ) {
		this.phasePAvoirEtatId = phasePAvoirEtatId;
	}
	
	public PhasePAvoirEtat(Integer phasePAvoirEtatId, Date pAvoirEtatFrom,
			Date pAvoirEtatTo, Phaseplanification phaseplanification,
			Etatphase etatphase) {
		super();
		this.phasePAvoirEtatId = phasePAvoirEtatId;
		PAvoirEtatFrom = pAvoirEtatFrom;
		PAvoirEtatTo = pAvoirEtatTo;
		this.phaseplanification = phaseplanification;
		this.etatphase = etatphase;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PHASEPAVOIRETAT", unique = true, nullable = false)
	public Integer getPhasePAvoirEtatId() {
		return this.phasePAvoirEtatId;
	}

	public void setPhasePAvoirEtatId(Integer phasePAvoirEtatId ) {
		this.phasePAvoirEtatId = phasePAvoirEtatId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "P_AVOIR_ETAT_FROM", length = 10)
	public Date getPAvoirEtatFrom() {
		return this.PAvoirEtatFrom;
	}

	public void setPAvoirEtatFrom(Date PAvoirEtatFrom) {
		this.PAvoirEtatFrom = PAvoirEtatFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "P_AVOIR_ETAT_TO", length = 10)
	public Date getPAvoirEtatTo() {
		return this.PAvoirEtatTo;
	}

	public void setPAvoirEtatTo(Date PAvoirEtatTo) {
		this.PAvoirEtatTo = PAvoirEtatTo;
	}

	@ManyToOne
	@JoinColumn(name="IDPHASE_P", referencedColumnName="IDPHASE_P")
	public Phaseplanification getPhaseplanification() {
		return phaseplanification;
	}

	public void setPhaseplanification(Phaseplanification phaseplanification) {
		this.phaseplanification = phaseplanification;
	}

	@ManyToOne
	@JoinColumn(name="IDETATPHASE", referencedColumnName="IDETATPHASE")
	public Etatphase getEtatphase() {
		return etatphase;
	}

	public void setEtatphase(Etatphase etatphase) {
		this.etatphase = etatphase;
	}
}
