package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Phaseretroplanification generated by hbm2java
 */
@Entity
@Table(name = "PHASERETROPLANIFICATION", catalog = "ralidb")
public class Phaseretroplanification implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idphaseRp;
//	private Integer idphaseRpPere;
//	private Integer idprojet;
	private String lblphaseRp;
	private String descphaseRp;
	private Integer profondphaseRp;
	private Date datedebphaseRp;
	private Date datefinphaseRp;
	private Phaseretroplanification phaseretroplanification;
	private Projet projet;
	private List<Phaseretroplanification> phasesretroplanification;
	private List<Contenuoptimise> rapportsactivites;
	private List<Contenuoptimise> jourssemaines;
	private List<Retroaffectation> ressources;
	private List<PhaseRpAvoirEtat> etatsphases;	
	private List<Documentationphase> documentationsphase;	

	public Phaseretroplanification() {
	}

	public Phaseretroplanification(Integer idphaseRp, String lblphaseRp,
			String descphaseRp, Integer profondphaseRp, Date datedebphaseRp,
			Date datefinphaseRp,
			Phaseretroplanification phaseretroplanification, Projet projet,
			List<Phaseretroplanification> phasesretroplanification,
			List<Contenuoptimise> rapportsactivites,
			List<Contenuoptimise> jourssemaines,
			List<Retroaffectation> ressources,
			List<PhaseRpAvoirEtat> etatsphases,
			List<Documentationphase> documentationsphase) {
		super();
		this.idphaseRp = idphaseRp;
		this.lblphaseRp = lblphaseRp;
		this.descphaseRp = descphaseRp;
		this.profondphaseRp = profondphaseRp;
		this.datedebphaseRp = datedebphaseRp;
		this.datefinphaseRp = datefinphaseRp;
		this.phaseretroplanification = phaseretroplanification;
		this.projet = projet;
		this.phasesretroplanification = phasesretroplanification;
		this.rapportsactivites = rapportsactivites;
		this.jourssemaines = jourssemaines;
		this.ressources = ressources;
		this.etatsphases = etatsphases;
		this.documentationsphase = documentationsphase;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDPHASE_RP", unique = true, nullable = false)
	public Integer getIdphaseRp() {
		return this.idphaseRp;
	}

	public void setIdphaseRp(Integer idphaseRp) {
		this.idphaseRp = idphaseRp;
	}

//	@Column(name = "IDPHASE_RP_PERE")
//	public Integer getIdphaseRpPere() {
//		return this.idphaseRpPere;
//	}
//
//	public void setIdphaseRpPere(Integer idphaseRpPere) {
//		this.idphaseRpPere = idphaseRpPere;
//	}
//
//	@Column(name = "IDPROJET")
//	public Integer getIdprojet() {
//		return this.idprojet;
//	}
//
//	public void setIdprojet(Integer idprojet) {
//		this.idprojet = idprojet;
//	}

	@Column(name = "LBLPHASE_RP", length = 65535)
	@Length(max = 65535)
	public String getLblphaseRp() {
		return this.lblphaseRp;
	}

	public void setLblphaseRp(String lblphaseRp) {
		this.lblphaseRp = lblphaseRp;
	}

	@Column(name = "DESCPHASE_RP", length = 65535)
	@Length(max = 65535)
	public String getDescphaseRp() {
		return this.descphaseRp;
	}

	public void setDescphaseRp(String descphaseRp) {
		this.descphaseRp = descphaseRp;
	}

	@Column(name = "PROFONDPHASE_RP")
	public Integer getProfondphaseRp() {
		return this.profondphaseRp;
	}

	public void setProfondphaseRp(Integer profondphaseRp) {
		this.profondphaseRp = profondphaseRp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBPHASE_RP", length = 10)
	public Date getDatedebphaseRp() {
		return this.datedebphaseRp;
	}

	public void setDatedebphaseRp(Date datedebphaseRp) {
		this.datedebphaseRp = datedebphaseRp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINPHASE_RP", length = 10)
	public Date getDatefinphaseRp() {
		return this.datefinphaseRp;
	}

	public void setDatefinphaseRp(Date datefinphaseRp) {
		this.datefinphaseRp = datefinphaseRp;
	}

	@ManyToOne
	@JoinColumn(name="IDPHASE_RP_PERE", referencedColumnName="IDPHASE_RP")
	public Phaseretroplanification getPhaseretroplanification() {
		return phaseretroplanification;
	}

	public void setPhaseretroplanification(
			Phaseretroplanification phaseretroplanification) {
		this.phaseretroplanification = phaseretroplanification;
	}

	@ManyToOne
	@JoinColumn(name="IDPROJET", referencedColumnName="IDPROJET")
	public Projet getProjet() {
		return projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}
	
	@OneToMany(mappedBy="phaseretroplanification")
	public List<Phaseretroplanification> getPhasesretroplanification() {
		return phasesretroplanification;
	}

	public void setPhasesretroplanification(
			List<Phaseretroplanification> phasesretroplanification) {
		this.phasesretroplanification = phasesretroplanification;
	}

	@OneToMany(mappedBy="phaseretroplanification")
	public List<Contenuoptimise> getRapportsactivites() {
		return rapportsactivites;
	}

	public void setRapportsactivites(List<Contenuoptimise> rapportsactivites) {
		this.rapportsactivites = rapportsactivites;
	}

	@OneToMany(mappedBy="phaseretroplanification")
	public List<Contenuoptimise> getJourssemaines() {
		return jourssemaines;
	}

	public void setJourssemaines(List<Contenuoptimise> jourssemaines) {
		this.jourssemaines = jourssemaines;
	}

	@OneToMany(mappedBy="phaseretroplanification")
	public List<Retroaffectation> getRessources() {
		return ressources;
	}

	public void setRessources(List<Retroaffectation> ressources) {
		this.ressources = ressources;
	}
	
	@OneToMany(mappedBy="phaseretroplanification")
	public List<PhaseRpAvoirEtat> getEtatsphases() {
		return etatsphases;
	}

	public void setEtatsphases(List<PhaseRpAvoirEtat> etatsphases) {
		this.etatsphases = etatsphases;
	}
	
	@OneToMany(mappedBy="phaseretroplanification")
	public List<Documentationphase> getDocumentationsphase() {
		return documentationsphase;
	}

	public void setDocumentationsphase(List<Documentationphase> documentationsphase) {
		this.documentationsphase = documentationsphase;
	}
}