package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * PhaseRpAvoirEtat generated by hbm2java
 */
@Entity
@Table(name = "PHASE_RP_AVOIR_ETAT", catalog = "ralidb")
public class PhaseRpAvoirEtat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer phaseRpAvoirEtatId ;
	private Date rpAvoirEtatFrom;
	private Date rpAvoirEtatTo;
	private Phaseretroplanification phaseretroplanification;
	private Etatphase etatphase;

	public PhaseRpAvoirEtat() {
	}

	public PhaseRpAvoirEtat(Integer phaseRpAvoirEtatId) {
		this.phaseRpAvoirEtatId = phaseRpAvoirEtatId;
	}
	
	public PhaseRpAvoirEtat(Integer phaseRpAvoirEtatId, Date rpAvoirEtatFrom,
			Date rpAvoirEtatTo,
			Phaseretroplanification phaseretroplanification, Etatphase etatphase) {
		super();
		this.phaseRpAvoirEtatId = phaseRpAvoirEtatId;
		this.rpAvoirEtatFrom = rpAvoirEtatFrom;
		this.rpAvoirEtatTo = rpAvoirEtatTo;
		this.phaseretroplanification = phaseretroplanification;
		this.etatphase = etatphase;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AVOIRRPETAT", unique = true, nullable = false)
	public Integer getPhaseRpAvoirEtatId() {
		return this.phaseRpAvoirEtatId;
	}

	public void setPhaseRpAvoirEtatId(Integer phaseRpAvoirEtatId) {
		this.phaseRpAvoirEtatId = phaseRpAvoirEtatId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RP_AVOIR_ETAT_FROM", length = 10)
	public Date getRpAvoirEtatFrom() {
		return this.rpAvoirEtatFrom;
	}

	public void setRpAvoirEtatFrom(Date rpAvoirEtatFrom) {
		this.rpAvoirEtatFrom = rpAvoirEtatFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RP_AVOIR_ETAT_TO", length = 10)
	public Date getRpAvoirEtatTo() {
		return this.rpAvoirEtatTo;
	}

	public void setRpAvoirEtatTo(Date rpAvoirEtatTo) {
		this.rpAvoirEtatTo = rpAvoirEtatTo;
	}

	@ManyToOne
	@JoinColumn(name="IDPHASE_RP", referencedColumnName="IDPHASE_RP")
	public Phaseretroplanification getPhaseretroplanification() {
		return phaseretroplanification;
	}

	public void setPhaseretroplanification(
			Phaseretroplanification phaseretroplanification) {
		this.phaseretroplanification = phaseretroplanification;
	}

	@ManyToOne
	@JoinColumn(name="IDETATPHASE", referencedColumnName="IDETATPHASE")
	public Etatphase getEtatphase() {
		return etatphase;
	}

	public void setEtatphase(Etatphase etatphase) {
		this.etatphase = etatphase;
	}
}
