package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Prestataire generated by hbm2java
 */
@Entity
@Table(name = "PRESTATAIRE", catalog = "ralidb")
public class Prestataire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idprestataire;
	private String lblprestataire;
	private List<Prestation> prestations;

	public Prestataire() {
	}

	public Prestataire(Integer idprestataire, String lblprestataire,
			List<Prestation> prestations) {
		super();
		this.idprestataire = idprestataire;
		this.lblprestataire = lblprestataire;
		this.prestations = prestations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDPRESTATAIRE", unique = true, nullable = false)
	public Integer getIdprestataire() {
		return this.idprestataire;
	}

	public void setIdprestataire(Integer idprestataire) {
		this.idprestataire = idprestataire;
	}

	@Column(name = "LBLPRESTATAIRE", length = 65535)
	@Length(max = 65535)
	public String getLblprestataire() {
		return this.lblprestataire;
	}

	public void setLblprestataire(String lblprestataire) {
		this.lblprestataire = lblprestataire;
	}

	@OneToMany(mappedBy="prestataire")
	public List<Prestation> getPrestations() {
		return prestations;
	}

	public void setPrestations(List<Prestation> prestations) {
		this.prestations = prestations;
	}
}
