package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Prestation generated by hbm2java
 */
@Entity
@Table(name = "PRESTATION", catalog = "ralidb")
public class Prestation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idprestation;
//	private int idprojet;
//	private int idprestataire;
//	private int idtypeprest;
//	private Integer idorg;
	private Date dateprestation;
	private Long devisprestation;
	private Long factprestation;
	private String descprestation;
	private Long tauxeligibilte;
	private Typeprestataire typeprestataire;
	private Projet projet;
	private Organisation organisation;
	private Prestataire prestataire;

	public Prestation() {
	}
	
	public Prestation(Integer idprestation, Date dateprestation,
			Long devisprestation, Long factprestation, String descprestation,
			Long tauxeligibilte, Typeprestataire typeprestataire,
			Projet projet, Organisation organisation, Prestataire prestataire) {
		super();
		this.idprestation = idprestation;
		this.dateprestation = dateprestation;
		this.devisprestation = devisprestation;
		this.factprestation = factprestation;
		this.descprestation = descprestation;
		this.tauxeligibilte = tauxeligibilte;
		this.typeprestataire = typeprestataire;
		this.projet = projet;
		this.organisation = organisation;
		this.prestataire = prestataire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDPRESTATION", unique = true, nullable = false)
	public Integer getIdprestation() {
		return this.idprestation;
	}

	public void setIdprestation(Integer idprestation) {
		this.idprestation = idprestation;
	}

//	@Column(name = "IDPROJET", nullable = false)
//	public int getIdprojet() {
//		return this.idprojet;
//	}
//
//	public void setIdprojet(int idprojet) {
//		this.idprojet = idprojet;
//	}

//	@Column(name = "IDPRESTATAIRE", nullable = false)
//	public int getIdprestataire() {
//		return this.idprestataire;
//	}
//
//	public void setIdprestataire(int idprestataire) {
//		this.idprestataire = idprestataire;
//	}

//	@Column(name = "IDTYPEPREST", nullable = false)
//	public int getIdtypeprest() {
//		return this.idtypeprest;
//	}
//
//	public void setIdtypeprest(int idtypeprest) {
//		this.idtypeprest = idtypeprest;
//	}

//	@Column(name = "IDORG")
//	public Integer getIdorg() {
//		return this.idorg;
//	}
//
//	public void setIdorg(Integer idorg) {
//		this.idorg = idorg;
//	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEPRESTATION", length = 10)
	public Date getDateprestation() {
		return this.dateprestation;
	}

	public void setDateprestation(Date dateprestation) {
		this.dateprestation = dateprestation;
	}

	@Column(name = "DEVISPRESTATION", precision = 10, scale = 0)
	public Long getDevisprestation() {
		return this.devisprestation;
	}

	public void setDevisprestation(Long devisprestation) {
		this.devisprestation = devisprestation;
	}

	@Column(name = "FACTPRESTATION", precision = 10, scale = 0)
	public Long getFactprestation() {
		return this.factprestation;
	}

	public void setFactprestation(Long factprestation) {
		this.factprestation = factprestation;
	}

	@Column(name = "DESCPRESTATION", length = 65535)
	@Length(max = 65535)
	public String getDescprestation() {
		return this.descprestation;
	}

	public void setDescprestation(String descprestation) {
		this.descprestation = descprestation;
	}

	@Column(name = "TAUXELIGIBILTE", precision = 10, scale = 0)
	public Long getTauxeligibilte() {
		return this.tauxeligibilte;
	}

	public void setTauxeligibilte(Long tauxeligibilte) {
		this.tauxeligibilte = tauxeligibilte;
	}

	@ManyToOne
	@JoinColumn(name="IDTYPEPREST", referencedColumnName="IDTYPEPREST")
	public Typeprestataire getTypeprestataire() {
		return typeprestataire;
	}

	public void setTypeprestataire(Typeprestataire typeprestataire) {
		this.typeprestataire = typeprestataire;
	}

	@ManyToOne
	@JoinColumn(name="IDPROJET", referencedColumnName="IDPROJET")
	public Projet getProjet() {
		return projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@ManyToOne
	@JoinColumn(name="IDORG", referencedColumnName="IDORG")
	public Organisation getOrganisation() {
		return organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@ManyToOne
	@JoinColumn(name="IDPRESTATAIRE", referencedColumnName="IDPRESTATAIRE")
	public Prestataire getPrestataire() {
		return prestataire;
	}

	public void setPrestataire(Prestataire prestataire) {
		this.prestataire = prestataire;
	}
}
