package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "PROFIL", catalog = "ralidb")
public class Profil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idprofil;
	private String lblprofil;
	private List<Resshum> resshums;
	private List<Ggpsysteme> Ggpsystemes;

	public Profil() {
	}

	public Profil(int idprofil) {
		this.idprofil = idprofil;
	}

	public Profil(int idprofil, String lblprofil, List<Resshum> resshums, List<Ggpsysteme> ggpsystemes) {
		super();
		this.idprofil = idprofil;
		this.lblprofil = lblprofil;
		this.resshums = resshums;
		Ggpsystemes = ggpsystemes;
	}
			
	@Id
	@Column(name = "IDPROFIL", unique = true, nullable = false)
	public int getIdprofil() {
		return this.idprofil;
	}

	public void setIdprofil(int idprofil) {
		this.idprofil = idprofil;
	}

	@Column(name = "LBLPROFIL", length = 65535)
	@Length(max = 65535)
	public String getLblprofil() {
		return this.lblprofil;
	}

	public void setLblprofil(String lblprofil) {
		this.lblprofil = lblprofil;
	}

	@ManyToMany(mappedBy="profils")
	public List<Resshum> getResshums() {
		return resshums;
	}

	public void setResshums(List<Resshum> resshums) {
		this.resshums = resshums;
	}

	@ManyToMany(mappedBy="profils")
	public List<Ggpsysteme> getGgpsystemes() {
		return Ggpsystemes;
	}

	public void setGgpsystemes(List<Ggpsysteme> ggpsystemes) {
		Ggpsystemes = ggpsystemes;
	}		

}
