package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Projet generated by hbm2java
 */
@Entity
@Table(name = "PROJET", catalog = "ralidb")
public class Projet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idprojet;
//	private int idRessCdp;
	private String lblprojet;
	private String descprojet;
	private Date datedebprojet;
	private Date datefinproj;
	private List<Prestation> prestations;	
	private List<Phaseplanification> phasesplanifications;
	private List<Phaseretroplanification> phasesretroplanifications;
	private Ressource ressource;

	public Projet() {
	}

	public Projet(int idprojet) {
		this.idprojet = idprojet;
	}

	public Projet(Integer idprojet, String lblprojet, String descprojet,
			Date datedebprojet, Date datefinproj, List<Prestation> prestations,
			List<Phaseplanification> phasesplanifications,
			List<Phaseretroplanification> phasesretroplanifications,
			Ressource ressource) {
		super();
		this.idprojet = idprojet;
		this.lblprojet = lblprojet;
		this.descprojet = descprojet;
		this.datedebprojet = datedebprojet;
		this.datefinproj = datefinproj;
		this.prestations = prestations;
		this.phasesplanifications = phasesplanifications;
		this.phasesretroplanifications = phasesretroplanifications;
		this.ressource = ressource;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDPROJET", unique = true, nullable = false)
	public Integer getIdprojet() {
		return this.idprojet;
	}

	public void setIdprojet(Integer idprojet) {
		this.idprojet = idprojet;
	}

//	@Column(name = "ID_RESS_CDP", nullable = false)
//	public int getIdRessCdp() {
//		return this.idRessCdp;
//	}
//
//	public void setIdRessCdp(int idRessCdp) {
//		this.idRessCdp = idRessCdp;
//	}

	@Column(name = "LBLPROJET", length = 65535)
	@Length(max = 65535)
	public String getLblprojet() {
		return this.lblprojet;
	}

	public void setLblprojet(String lblprojet) {
		this.lblprojet = lblprojet;
	}

	@Column(name = "DESCPROJET", length = 65535)
	@Length(max = 65535)
	public String getDescprojet() {
		return this.descprojet;
	}

	public void setDescprojet(String descprojet) {
		this.descprojet = descprojet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBPROJET", length = 10)
	public Date getDatedebprojet() {
		return this.datedebprojet;
	}

	public void setDatedebprojet(Date datedebprojet) {
		this.datedebprojet = datedebprojet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINPROJ", length = 10)
	public Date getDatefinproj() {
		return this.datefinproj;
	}

	public void setDatefinproj(Date datefinproj) {
		this.datefinproj = datefinproj;
	}

	@OneToMany(mappedBy="projet")
	public List<Prestation> getPrestations() {
		return prestations;
	}

	public void setPrestations(List<Prestation> prestations) {
		this.prestations = prestations;
	}

	@OneToMany(mappedBy="projet")
	public List<Phaseplanification> getPhasesplanifications() {
		return phasesplanifications;
	}

	public void setPhasesplanifications(
			List<Phaseplanification> phasesplanifications) {
		this.phasesplanifications = phasesplanifications;
	}

	@OneToMany(mappedBy="projet")
	public List<Phaseretroplanification> getPhasesretroplanifications() {
		return phasesretroplanifications;
	}

	public void setPhasesretroplanifications(
			List<Phaseretroplanification> phasesretroplanifications) {
		this.phasesretroplanifications = phasesretroplanifications;
	}
	
	@ManyToOne
	@JoinColumn(name="ID_RESS_CDP", referencedColumnName="IDRESS")
	public Ressource getRessource() {
		return ressource;
	}

	public void setRessource(Ressource ressource) {
		this.ressource = ressource;
	}
}
