package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA


import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import org.hibernate.validator.Length;

/**
 * Rapportactivites generated by hbm2java
 */
@Entity
@Table(name = "RAPPORTACTIVITES", catalog = "ralidb")
public class Rapportactivites implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idrapactv;
	private String anneera;
	private String semainera;
	private List<Contenuoptimise> phasesretroplanification;		
	private Ressource ressource;
	private List<Contenu> jourssemaines;
	private List<Contenu> phasesplanification;
	private List<Contenuoptimise> jourssemainesOptm;

	public Rapportactivites() {
	}

	public Rapportactivites(int idrapactv) {
		this.idrapactv = idrapactv;
	}

	public Rapportactivites(Integer idrapactv, Ressource ressource, String anneera,String semainera) {
		super();
		this.idrapactv = idrapactv;
		this.ressource = ressource;
		this.anneera = anneera;
		this.semainera = semainera;
	}

	public Rapportactivites(Integer idrapactv, String anneera,
			String semainera, List<Contenuoptimise> phasesretroplanification,
			Ressource ressource, List<Contenu> jourssemaines,
			List<Contenu> phasesplanification,
			List<Contenuoptimise> jourssemainesOptm) {
		super();
		this.idrapactv = idrapactv;
		this.anneera = anneera;
		this.semainera = semainera;
		this.phasesretroplanification = phasesretroplanification;
		this.ressource = ressource;
		this.jourssemaines = jourssemaines;
		this.phasesplanification = phasesplanification;
		this.jourssemainesOptm = jourssemainesOptm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDRAPACTV", unique = true, nullable = false)
	public Integer getIdrapactv() {
		return this.idrapactv;
	}

	public void setIdrapactv(Integer idrapactv) {
		this.idrapactv = idrapactv;
	}

	@Column(name = "ANNEE", length = 4)
	@Length(max = 4)
	public String getAnneera() {
		return this.anneera;
	}

	public void setAnneera(String anneera) {
		this.anneera = anneera;
	}

	@Column(name = "NUMSEMAINE", length = 3)
	@Length(max = 3)
	public String getSemainera() {
		return this.semainera;
	}

	public void setSemainera(String semainera) {
		this.semainera = semainera;
	}

	@OneToMany(cascade={CascadeType.ALL}, mappedBy="rapportactivites")
	public List<Contenuoptimise> getPhasesretroplanification() {
		return phasesretroplanification;
	}

	public void setPhasesretroplanification(
			List<Contenuoptimise> phasesretroplanification) {
		this.phasesretroplanification = phasesretroplanification;
	}

	@ManyToOne
	@JoinColumn(name="IDRESS", referencedColumnName="IDRESS")
	public Ressource getRessource() {
		return ressource;
	}

	public void setRessource(Ressource ressource) {
		this.ressource = ressource;
	}

	@OneToMany(cascade={CascadeType.ALL}, mappedBy="rapportactivites")
	public List<Contenu> getJourssemaines() {
		return jourssemaines;
	}

	public void setJourssemaines(List<Contenu> jourssemaines) {
		this.jourssemaines = jourssemaines;
	}

	@OneToMany(cascade={CascadeType.ALL}, mappedBy="rapportactivites")
	public List<Contenu> getPhasesplanification() {
		return phasesplanification;
	}

	public void setPhasesplanification(List<Contenu> phasesplanification) {
		this.phasesplanification = phasesplanification;
	}

	@OneToMany(cascade={CascadeType.ALL}, mappedBy="rapportactivites")
	public List<Contenuoptimise> getJourssemainesOptm() {
		return jourssemainesOptm;
	}

	public void setJourssemainesOptm(List<Contenuoptimise> jourssemainesOptm) {
		this.jourssemainesOptm = jourssemainesOptm;
	}
	
	@Override
	public String toString() {
		return "Rapportactivites [anneera=" + anneera + ", idrapactv="
				+ idrapactv + ", semainera=" + semainera + "]";
	}

	
}
