package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Ressamort generated by hbm2java
 */
@Entity
@Table(name = "RESSAMORT", catalog = "ralidb")
@PrimaryKeyJoinColumn(name="IDRESS")
public class Ressamort extends Ressource implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
//	private Integer idress;
	private String designationra;
	private Date dateacquisitionra;
	private Long valacquisitionra;
	private List<Amortissment> amortissments;

	public Ressamort() {
	}

public Ressamort(String designationra, Date dateacquisitionra,
			Long valacquisitionra, List<Amortissment> amortissments) {
		super();
		this.designationra = designationra;
		this.dateacquisitionra = dateacquisitionra;
		this.valacquisitionra = valacquisitionra;
		this.amortissments = amortissments;
	}

//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//	@Column(name = "IDRESS", unique = true, nullable = false)
//	public Integer getIdress() {
//		return this.idress;
//	}
//
//	public void setIdress(Integer idress) {
//		this.idress = idress;
//	}

	@Column(name = "DESIGNATIONRA", length = 65535)
	@Length(max = 65535)
	public String getDesignationra() {
		return this.designationra;
	}

	public void setDesignationra(String designationra) {
		this.designationra = designationra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEACQUISITIONRA", length = 10)
	public Date getDateacquisitionra() {
		return this.dateacquisitionra;
	}

	public void setDateacquisitionra(Date dateacquisitionra) {
		this.dateacquisitionra = dateacquisitionra;
	}

	@Column(name = "VALACQUISITIONRA", precision = 10, scale = 0)
	public Long getValacquisitionra() {
		return this.valacquisitionra;
	}

	public void setValacquisitionra(Long valacquisitionra) {
		this.valacquisitionra = valacquisitionra;
	}

	@OneToMany(mappedBy="ressamort")
	public List<Amortissment> getAmortissments() {
		return amortissments;
	}

	public void setAmortissments(List<Amortissment> amortissments) {
		this.amortissments = amortissments;
	}
}
