package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.Entity;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.jboss.seam.annotations.Name;

/**
 * Resshum generated by hbm2java
 */
@Entity
@Table(name = "RESSHUM", catalog = "ralidb")
@PrimaryKeyJoinColumn(name="IDRESS")
@Name("Resshum")
public class Resshum extends Ressource implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String nomrh;
	private String prenomrh;
	private String acronyme;
	private Date dateembauche;
	private Boolean isfirstcdi;
	private String loging;
	private String emailrh;
	private String pwdrh;
	private List<Profil> profils;	
	private List<Avoirdiplome> diplomes;	
	private List<RhAvoirStatut> statuts;	
	private List<Coordonnees> coordonnees;	
	private List<Chargespatronales> chargespatronales;	
	private List<Salairebrut> salairesbruts;	
	private List<Amortissment> amortissments;
	
	public Resshum() {
	}

	public Resshum(String nomrh, String prenomrh, String acronyme,
			Date dateembauche, Boolean isfirstcdi, String loging,
			String emailrh, String pwdrh, List<Profil> profils,
			List<Avoirdiplome> diplomes, List<RhAvoirStatut> statuts,
			List<Coordonnees> coordonnees,
			List<Chargespatronales> chargespatronales,
			List<Salairebrut> salairesbruts, List<Amortissment> amortissments) {
		super();
		this.nomrh = nomrh;
		this.prenomrh = prenomrh;
		this.acronyme = acronyme;
		this.dateembauche = dateembauche;
		this.isfirstcdi = isfirstcdi;
		this.loging = loging;
		this.emailrh = emailrh;
		this.pwdrh = pwdrh;
		this.profils = profils;
		this.diplomes = diplomes;
		this.statuts = statuts;
		this.coordonnees = coordonnees;
		this.chargespatronales = chargespatronales;
		this.salairesbruts = salairesbruts;
		this.amortissments = amortissments;
	}

	@Column(name = "NOMRH", length = 65535)
	@Length(max = 65535)
	public String getNomrh() {
		return this.nomrh;
	}

	public void setNomrh(String nomrh) {
		this.nomrh = nomrh;
	}

	@Column(name = "PRENOMRH", length = 65535)
	@Length(max = 65535)
	public String getPrenomrh() {
		return this.prenomrh;
	}

	public void setPrenomrh(String prenomrh) {
		this.prenomrh = prenomrh;
	}

	@Column(name = "ACRONYME", length = 65535)
	@Length(max = 65535)
	public String getAcronyme() {
		return this.acronyme;
	}

	public void setAcronyme(String acronyme) {
		this.acronyme = acronyme;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEEMBAUCHE", length = 10)
	public Date getDateembauche() {
		return this.dateembauche;
	}

	public void setDateembauche(Date dateembauche) {
		this.dateembauche = dateembauche;
	}

	@Column(name = "ISFIRSTCDI")
	public Boolean getIsfirstcdi() {
		return this.isfirstcdi;
	}

	public void setIsfirstcdi(Boolean isfirstcdi) {
		this.isfirstcdi = isfirstcdi;
	}

	@Column(name = "LOGING", length = 65535)
	@Length(max = 65535)
	public String getLoging() {
		return this.loging;
	}

	public void setLoging(String loging) {
		this.loging = loging;
	}

	@Column(name = "EMAILRH", length = 65535)
	@Length(max = 65535)
	public String getEmailrh() {
		return this.emailrh;
	}

	public void setEmailrh(String emailrh) {
		this.emailrh = emailrh;
	}

	@Column(name = "PWDRH", length = 65535)
	@Length(max = 65535)
	public String getPwdrh() {
		return this.pwdrh;
	}

	public void setPwdrh(String pwdrh) {
		this.pwdrh = pwdrh;
	}

	@ManyToMany
	@JoinTable(
			name="RH_AVOIR_PROFIL",
			joinColumns={@JoinColumn(name="IDRESS", referencedColumnName="idress")},
			inverseJoinColumns={@JoinColumn(name="IDPROFIL", referencedColumnName="idprofil")})
	public List<Profil> getProfils() {
		return profils;
	}

	public void setProfils(List<Profil> profils) {
		this.profils = profils;
	}
	
	@OneToMany(mappedBy="resshum")
	public List<Avoirdiplome> getDiplomes() {
		return diplomes;
	}

	public void setDiplomes(List<Avoirdiplome> diplomes) {
		this.diplomes = diplomes;
	}

	@OneToMany(mappedBy="resshum")
	public List<RhAvoirStatut> getStatuts() {
		return statuts;
	}

	public void setStatuts(List<RhAvoirStatut> statuts) {
		this.statuts = statuts;
	}

	@OneToMany(mappedBy="resshum")
	public List<Coordonnees> getCoordonnees() {
		return coordonnees;
	}

	public void setCoordonnees(List<Coordonnees> coordonnees) {
		this.coordonnees = coordonnees;
	}

	@OneToMany(mappedBy="resshum")
	public List<Chargespatronales> getChargespatronales() {
		return chargespatronales;
	}

	public void setChargespatronales(List<Chargespatronales> chargespatronales) {
		this.chargespatronales = chargespatronales;
	}

	@OneToMany(mappedBy="resshum")
	public List<Salairebrut> getSalairesbruts() {
		return salairesbruts;
	}

	public void setSalairesbruts(List<Salairebrut> salairesbruts) {
		this.salairesbruts = salairesbruts;
	}

	
	@OneToMany(mappedBy="resshum")
	public List<Amortissment> getAmortissments() {
		return amortissments;
	}

	public void setAmortissments(List<Amortissment> amortissments) {
		this.amortissments = amortissments;
	}
}
