package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Retroaffectation generated by hbm2java
 */
@Entity
@Table(name = "RETROAFFECTATION", catalog = "ralidb")
public class Retroaffectation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer retroaffectationId ;
	private Date datedebreaffect;
	private Date datefinreaffect;
	private Phaseretroplanification phaseretroplanification;
	private Ressource ressource;

	public Retroaffectation() {
	}

	public Retroaffectation(Integer retroaffectationId) {
		this.retroaffectationId = retroaffectationId;
	}

	public Retroaffectation(Integer retroaffectationId , Date datedebreaffect,
			Date datefinreaffect,
			Phaseretroplanification phaseretroplanification, Ressource ressource) {
		super();
		this.retroaffectationId = retroaffectationId;
		this.datedebreaffect = datedebreaffect;
		this.datefinreaffect = datefinreaffect;
		this.phaseretroplanification = phaseretroplanification;
		this.ressource = ressource;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RETROAFFECTATIONID", unique = true, nullable = false)
	public Integer getRetroaffectationId() {
		return this.retroaffectationId;
	}

	public void setRetroaffectationId(Integer retroaffectationId) {
		this.retroaffectationId = retroaffectationId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBREAFFECT", length = 10)
	public Date getDatedebreaffect() {
		return this.datedebreaffect;
	}

	public void setDatedebreaffect(Date datedebreaffect) {
		this.datedebreaffect = datedebreaffect;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINREAFFECT", length = 10)
	public Date getDatefinreaffect() {
		return this.datefinreaffect;
	}

	public void setDatefinreaffect(Date datefinreaffect) {
		this.datefinreaffect = datefinreaffect;
	}

	@ManyToOne
	@JoinColumn(name="IDPHASE_RP", referencedColumnName="IDPHASE_RP")
	public Phaseretroplanification getPhaseretroplanification() {
		return phaseretroplanification;
	}

	public void setPhaseretroplanification(
			Phaseretroplanification phaseretroplanification) {
		this.phaseretroplanification = phaseretroplanification;
	}

	@ManyToOne
	@JoinColumn(name="IDRESS", referencedColumnName="IDRESS")
	public Ressource getRessource() {
		return ressource;
	}

	public void setRessource(Ressource ressource) {
		this.ressource = ressource;
	}
}
