package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RhAvoirProfil generated by hbm2java
 */
@Entity
@Table(name = "RH_AVOIR_PROFIL", catalog = "ralidb")
public class RhAvoirProfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rhAvoirProfilId;
	private int idress;
	private int idprofil;

	public RhAvoirProfil() {
	}

	public RhAvoirProfil(Integer rhAvoirProfilId) {
		this.rhAvoirProfilId = rhAvoirProfilId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RHAVOIRPROFILID", unique = true, nullable = false)
	public Integer getRhAvoirProfilId() {
		return this.rhAvoirProfilId;
	}

	public void setRhAvoirProfilId(Integer rhAvoirProfilId) {
		this.rhAvoirProfilId = rhAvoirProfilId;
	}

	public void setIdress(int idress) {
		this.idress = idress;
	}

	public int getIdress() {
		return idress;
	}

	public void setIdprofil(int idprofil) {
		this.idprofil = idprofil;
	}

	public int getIdprofil() {
		return idprofil;
	}

}
