package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA
import static javax.persistence.GenerationType.IDENTITY;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * RhAvoirStatut generated by hbm2java
 */
@Entity
@Table(name = "RH_AVOIR_STATUT", catalog = "ralidb")
public class RhAvoirStatut implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer avoirStatutId;
	private Date rhAvoirStatutFrom;
	private Date rhAvoirStatutTo;
	private Resshum resshum;
	private Statut statut;	

	public RhAvoirStatut() {
	}

	public RhAvoirStatut(Integer avoirStatutId) {
		this.avoirStatutId= avoirStatutId;
	}	

	public RhAvoirStatut(Integer avoirStatutId, Date rhAvoirStatutFrom,
			Date rhAvoirStatutTo, Resshum resshum, Statut statut) {
		super();
		this.avoirStatutId = avoirStatutId;
		this.rhAvoirStatutFrom = rhAvoirStatutFrom;
		this.rhAvoirStatutTo = rhAvoirStatutTo;
		this.resshum = resshum;
		this.statut = statut;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "avoirStatutId", unique = true, nullable = false)
	public Integer getAvoirStatutId() {
		return this.avoirStatutId;
	}

	public void setAvoirStatutId(Integer avoirStatutId) {
		this.avoirStatutId = avoirStatutId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RH_AVOIR_STATUT_FROM", length = 10)
	public Date getRhAvoirStatutFrom() {
		return this.rhAvoirStatutFrom;
	}

	public void setRhAvoirStatutFrom(Date rhAvoirStatutFrom) {
		this.rhAvoirStatutFrom = rhAvoirStatutFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RH_AVOIR_STATUT_TO", length = 10)
	public Date getRhAvoirStatutTo() {
		return this.rhAvoirStatutTo;
	}

	public void setRhAvoirStatutTo(Date rhAvoirStatutTo) {
		this.rhAvoirStatutTo = rhAvoirStatutTo;
	}

	@ManyToOne
	@JoinColumn(name="IDRESS", referencedColumnName="IDRESS")
	public Resshum getResshum() {
		return resshum;
	}

	public void setResshum(Resshum resshum) {
		this.resshum = resshum;
	}

	@ManyToOne
	@JoinColumn(name="IDSTATUT", referencedColumnName="IDSTATUT")
	public Statut getStatut() {
		return statut;
	}

	public void setStatut(Statut statut) {
		this.statut = statut;
	}	
}
