package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salairebrut generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SALAIREBRUT", catalog = "ralidb")
public class Salairebrut implements java.io.Serializable {

	private int idsb;
	private Date sbFrom;
	private Date sbTo;
	private Long sbValeur;
	private Resshum resshum;
	
	public Salairebrut() {
	}


	public Salairebrut(int idsb, Date sbFrom, Date sbTo, Long sbValeur,
			Resshum resshum) {
		super();
		this.idsb = idsb;
		this.sbFrom = sbFrom;
		this.sbTo = sbTo;
		this.sbValeur = sbValeur;
		this.resshum = resshum;
	}


	@Id
	@Column(name = "IDSB", unique = true, nullable = false)
	public int getIdsb() {
		return this.idsb;
	}

	public void setIdsb(int idsb) {
		this.idsb = idsb;
	}

//	@Column(name = "IDRESS", nullable = false)
//	public int getIdress() {
//		return this.idress;
//	}
//
//	public void setIdress(int idress) {
//		this.idress = idress;
//	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SB_FROM", length = 10)
	public Date getSbFrom() {
		return this.sbFrom;
	}

	public void setSbFrom(Date sbFrom) {
		this.sbFrom = sbFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SB_TO", length = 10)
	public Date getSbTo() {
		return this.sbTo;
	}

	public void setSbTo(Date sbTo) {
		this.sbTo = sbTo;
	}

	@Column(name = "SB_valeur", precision = 10, scale = 0)
	public Long getSbValeur() {
		return this.sbValeur;
	}

	public void setSbValeur(Long sbValeur) {
		this.sbValeur = sbValeur;
	}

	@ManyToOne
	@JoinColumn(name="IDRESS", referencedColumnName="IDRESS")
	public Resshum getResshum() {
		return resshum;
	}

	public void setResshum(Resshum resshum) {
		this.resshum = resshum;
	}
}
