package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SimulationcirScir generated by hbm2java
 */
@Entity
@Table(name = "SIMULATIONCIR_SCIR", catalog = "ralidb")
public class SimulationcirScir implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idscir;
	private Date datescir;
	private Long dotamort;
	private Long depperschertech;
	private Long deppersjd;
	private Long depfct;
	private Long prisemaintbrevt;
	private Long depdefbrvt;
	private Long dotamortbrvt;
	private Long moitsalchrg;
	private Long autrdepnorm;
	private Long moitdep;
	private Long prestpub;
	private Long prestprivagr;
	private Long veilltechno;
	private Long textil;
	private Long soustrait;
	private List<Dossiercir> ggpsystemes;	
	private List<Dossiercir> entreprises;

	public SimulationcirScir() {
	}

	public SimulationcirScir(int idscir) {
		this.idscir = idscir;
	}

	public SimulationcirScir(int idscir, Date datescir, Long dotamort,
			Long depperschertech, Long deppersjd, Long depfct,
			Long prisemaintbrevt, Long depdefbrvt, Long dotamortbrvt,
			Long moitsalchrg, Long autrdepnorm, Long moitdep, Long prestpub,
			Long prestprivagr, Long veilltechno, Long textil, Long soustrait,
			List<Dossiercir> ggpsystemes, List<Dossiercir> entreprises) {
		super();
		this.idscir = idscir;
		this.datescir = datescir;
		this.dotamort = dotamort;
		this.depperschertech = depperschertech;
		this.deppersjd = deppersjd;
		this.depfct = depfct;
		this.prisemaintbrevt = prisemaintbrevt;
		this.depdefbrvt = depdefbrvt;
		this.dotamortbrvt = dotamortbrvt;
		this.moitsalchrg = moitsalchrg;
		this.autrdepnorm = autrdepnorm;
		this.moitdep = moitdep;
		this.prestpub = prestpub;
		this.prestprivagr = prestprivagr;
		this.veilltechno = veilltechno;
		this.textil = textil;
		this.soustrait = soustrait;
		this.ggpsystemes = ggpsystemes;
		this.entreprises = entreprises;
	}

	@Id
	@Column(name = "IDSCIR", unique = true, nullable = false)
	public int getIdscir() {
		return this.idscir;
	}

	public void setIdscir(int idscir) {
		this.idscir = idscir;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATESCIR", length = 10)
	public Date getDatescir() {
		return this.datescir;
	}

	public void setDatescir(Date datescir) {
		this.datescir = datescir;
	}

	@Column(name = "DOTAMORT", precision = 10, scale = 0)
	public Long getDotamort() {
		return this.dotamort;
	}

	public void setDotamort(Long dotamort) {
		this.dotamort = dotamort;
	}

	@Column(name = "DEPPERSCHERTECH", precision = 10, scale = 0)
	public Long getDepperschertech() {
		return this.depperschertech;
	}

	public void setDepperschertech(Long depperschertech) {
		this.depperschertech = depperschertech;
	}

	@Column(name = "DEPPERSJD", precision = 10, scale = 0)
	public Long getDeppersjd() {
		return this.deppersjd;
	}

	public void setDeppersjd(Long deppersjd) {
		this.deppersjd = deppersjd;
	}

	@Column(name = "DEPFCT", precision = 10, scale = 0)
	public Long getDepfct() {
		return this.depfct;
	}

	public void setDepfct(Long depfct) {
		this.depfct = depfct;
	}

	@Column(name = "PRISEMAINTBREVT", precision = 10, scale = 0)
	public Long getPrisemaintbrevt() {
		return this.prisemaintbrevt;
	}

	public void setPrisemaintbrevt(Long prisemaintbrevt) {
		this.prisemaintbrevt = prisemaintbrevt;
	}

	@Column(name = "DEPDEFBRVT", precision = 10, scale = 0)
	public Long getDepdefbrvt() {
		return this.depdefbrvt;
	}

	public void setDepdefbrvt(Long depdefbrvt) {
		this.depdefbrvt = depdefbrvt;
	}

	@Column(name = "DOTAMORTBRVT", precision = 10, scale = 0)
	public Long getDotamortbrvt() {
		return this.dotamortbrvt;
	}

	public void setDotamortbrvt(Long dotamortbrvt) {
		this.dotamortbrvt = dotamortbrvt;
	}

	@Column(name = "MOITSALCHRG", precision = 10, scale = 0)
	public Long getMoitsalchrg() {
		return this.moitsalchrg;
	}

	public void setMoitsalchrg(Long moitsalchrg) {
		this.moitsalchrg = moitsalchrg;
	}

	@Column(name = "AUTRDEPNORM", precision = 10, scale = 0)
	public Long getAutrdepnorm() {
		return this.autrdepnorm;
	}

	public void setAutrdepnorm(Long autrdepnorm) {
		this.autrdepnorm = autrdepnorm;
	}

	@Column(name = "MOITDEP", precision = 10, scale = 0)
	public Long getMoitdep() {
		return this.moitdep;
	}

	public void setMoitdep(Long moitdep) {
		this.moitdep = moitdep;
	}

	@Column(name = "PRESTPUB", precision = 10, scale = 0)
	public Long getPrestpub() {
		return this.prestpub;
	}

	public void setPrestpub(Long prestpub) {
		this.prestpub = prestpub;
	}

	@Column(name = "PRESTPRIVAGR", precision = 10, scale = 0)
	public Long getPrestprivagr() {
		return this.prestprivagr;
	}

	public void setPrestprivagr(Long prestprivagr) {
		this.prestprivagr = prestprivagr;
	}

	@Column(name = "VEILLTECHNO", precision = 10, scale = 0)
	public Long getVeilltechno() {
		return this.veilltechno;
	}

	public void setVeilltechno(Long veilltechno) {
		this.veilltechno = veilltechno;
	}

	@Column(name = "TEXTIL", precision = 10, scale = 0)
	public Long getTextil() {
		return this.textil;
	}

	public void setTextil(Long textil) {
		this.textil = textil;
	}

	@Column(name = "SOUSTRAIT", precision = 10, scale = 0)
	public Long getSoustrait() {
		return this.soustrait;
	}

	public void setSoustrait(Long soustrait) {
		this.soustrait = soustrait;
	}
	@OneToMany(mappedBy="simulationcirScir")
	public List<Dossiercir> getGgpsystemes() {
		return ggpsystemes;
	}

	public void setGgpsystemes(List<Dossiercir> ggpsystemes) {
		this.ggpsystemes = ggpsystemes;
	}
	@OneToMany(mappedBy="simulationcirScir")
	public List<Dossiercir> getEntreprises() {
		return entreprises;
	}

	public void setEntreprises(List<Dossiercir> entreprises) {
		this.entreprises = entreprises;
	}	
}
