package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Statut generated by hbm2java
 */
@Entity
@Table(name = "STATUT", catalog = "ralidb")
public class Statut implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idstatut;
	private String lblstatut;
	private List<RhAvoirStatut> resshums;

	public Statut() {
	}

	public Statut(Integer idstatut, String lblstatut,
			List<RhAvoirStatut> resshums) {
		super();
		this.idstatut = idstatut;
		this.lblstatut = lblstatut;
		this.resshums = resshums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDSTATUT", unique = true, nullable = false)
	public Integer getIdstatut() {
		return this.idstatut;
	}

	public void setIdstatut(Integer idstatut) {
		this.idstatut = idstatut;
	}

	@Column(name = "LBLSTATUT", length = 65535)
	@Length(max = 65535)
	public String getLblstatut() {
		return this.lblstatut;
	}

	public void setLblstatut(String lblstatut) {
		this.lblstatut = lblstatut;
	}
	
	@OneToMany(mappedBy="statut")
	public List<RhAvoirStatut> getResshums() {
		return resshums;
	}

	public void setResshums(List<RhAvoirStatut> resshums) {
		this.resshums = resshums;
	}
}
