package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Tache generated by hbm2java
 */
@Entity
@Table(name = "TACHE", catalog = "ralidb")
public class Tache implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idtache;
	private String lbltache;
	private List<Contenu> contenus;
	private List<Contenuoptimise> contenuoptimises;

	public Tache() {
	}

	public Tache(Integer idtache, String lbltache, List<Contenu> contenus, List<Contenuoptimise> contenuoptimises) {
		super();
		this.idtache = idtache;
		this.lbltache = lbltache;
		this.contenus = contenus;
		this.contenuoptimises = contenuoptimises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDTACHE", unique = true, nullable = false)
	public Integer getIdtache() {
		return this.idtache;
	}

	public void setIdtache(Integer idtache) {
		this.idtache = idtache;
	}

	@Column(name = "LBLTACHE", length = 65535)
	@Length(max = 65535)
	public String getLbltache() {
		return this.lbltache;
	}

	public void setLbltache(String lbltache) {
		this.lbltache = lbltache;
	}
	
	@OneToMany(mappedBy="tache")
	public List<Contenu> getContenus() {
		return contenus;
	}

	public void setContenus(List<Contenu> contenus) {
		this.contenus = contenus;
	}
		
	@OneToMany(mappedBy="tache")
	public List<Contenuoptimise> getContenuoptimises() {
		return contenuoptimises;
	}

	public void setContenuoptimises(List<Contenuoptimise> contenuoptimises) {
		this.contenuoptimises = contenuoptimises;
	}

}
