package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Typeprestataire generated by hbm2java
 */
@Entity
@Table(name = "TYPEPRESTATAIRE", catalog = "ralidb")
public class Typeprestataire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idtypeprest;
	private String lbltypeprest;
	private List<Prestation> prestations;	

	public Typeprestataire() {
	}

	public Typeprestataire(Integer idtypeprest, String lbltypeprest,
			List<Prestation> prestations) {
		super();
		this.idtypeprest = idtypeprest;
		this.lbltypeprest = lbltypeprest;
		this.prestations = prestations;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDTYPEPREST", unique = true, nullable = false)
	public Integer getIdtypeprest() {
		return this.idtypeprest;
	}

	public void setIdtypeprest(Integer idtypeprest) {
		this.idtypeprest = idtypeprest;
	}

	@Column(name = "LBLTYPEPREST", length = 65535)
	@Length(max = 65535)
	public String getLbltypeprest() {
		return this.lbltypeprest;
	}

	public void setLbltypeprest(String lbltypeprest) {
		this.lbltypeprest = lbltypeprest;
	}

	@OneToMany(mappedBy="typeprestataire")
	public List<Prestation> getPrestations() {
		return prestations;
	}

	public void setPrestations(List<Prestation> prestations) {
		this.prestations = prestations;
	}
}
