package com.glaizer.RaliProject.model;
// Generated 12 juil. 2010 14:28:03 by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Typecoordonnees generated by hbm2java
 */
@Entity
@Table(name = "TYPECOORDONNEES", catalog = "ralidb")
public class Typecoordonnees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idtypecoord;
	private String lbltypecoord;
	private List<Coordonnees> coordonnees;

	public Typecoordonnees() {
	}

	public Typecoordonnees(Integer idtypecoord, String lbltypecoord,
			List<Coordonnees> coordonnees) {
		super();
		this.idtypecoord = idtypecoord;
		this.lbltypecoord = lbltypecoord;
		this.coordonnees = coordonnees;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDTYPECOORD", unique = true, nullable = false)
	public Integer getIdtypecoord() {
		return this.idtypecoord;
	}

	public void setIdtypecoord(Integer idtypecoord) {
		this.idtypecoord = idtypecoord;
	}

	@Column(name = "LBLTYPECOORD", length = 65535)
	@Length(max = 65535)
	public String getLbltypecoord() {
		return this.lbltypecoord;
	}

	public void setLbltypecoord(String lbltypecoord) {
		this.lbltypecoord = lbltypecoord;
	}

	@OneToMany(mappedBy="typecoordonnee")
	public List<Coordonnees> getCoordonnees() {
		return coordonnees;
	}

	public void setCoordonnees(List<Coordonnees> coordonnees) {
		this.coordonnees = coordonnees;
	}
}
